eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  server:
#    enable-self-preservation: false
#  instance:
#自定义
#    hostname: clientName
  
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/120591516/springCloud-parent
          searchPaths: configFolder
  application:
    name: config-server