eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/120591516/springCloud-parent
          searchPaths: spring-cloud/configFolder
  application:
    name: config-server