server:
  port: 8051
spring:
  application:
    name: service-sidecar
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level: info
sidecar:
  #node启动监听端口
  port: 8060
  health-uri: http://localhost:8060/health.json
